# Basic
title: 陈草头
subtitle: 越名教而任自然
welcome_message: <a href="https://caotouchan.tech" target="_blank">我的主页</a>
description: 90 后 | 广东人 | 现居住于帝都 | 算法攻城狮
creator: <a href="https://caotouchan.tech">@caotouchan</a>

url: "http://caotouchan.tech/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    # - {title: 搜索, description: 搜索博客文章, url: 'https://caotouchan.tech/2000/06/search'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: caotouchan
    # duoshuo: 
    gitalk: true

gitalk:
  clientID: 6005df5e831456f4482b                            #生成的clientID
  clientSecret: ffc57d242198e14cdb68b7457a765d0b719415fb    #生成的clientSecret
  repo: caotouchan.github.io    #仓库名称
  owner: CaoTouChan    #github用户名
  admin: CaoTouChan
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
    
# Social
social:
    weibo: lookka520
    github: caotouchan
    mail: caotouchan@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
